AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  CloudNonceDiscovery:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 1024
      Timeout: 30
      Role: >-
        arn:aws:iam::993598138204:role/service-role/CloudNonceDiscovery-role-h158qjdc
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /CloudNonceDiscovery
            Method: ANY
